export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_CHAT_ROOMS = 'SET_CHAT_ROOMS';
export const SET_ROOM_DETAILS = 'SET_ROOM_DETAILS';
export const SET_ROOM_MESSAGES = 'SET_ROOM_MESSAGES';
