export const REQUEST = 'REQUEST';
export const FAILURE = 'FAILURE';

export const SET_USER_NAME = 'SET_USER_NAME';
export const CHAT_ROOMS_SUCCESS = 'CHAT_ROOMS_SUCCESS';

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_MESSAGES_SUCCESS = 'ROOM_MESSAGES_SUCCESS';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_SUCCESS= 'UPDATE_MESSAGE_SUCCESS';

export const SET_PUSH_NOTIFICATION = 'SET_PUSH_NOTIFICATION';
